version: '3.1'

services:

  bot:
    build: services/discord_bot
    container_name: discord_bot
    depends_on:
      - mongo
    env_file:
      - services/discord_bot/.env
    environment:
      - MONGO_URL=mongodb://root:passwordRoot@mongo:27017/
      - LOGS=logs/infos.log
      - GOOGLECREDENTIALS=service/googleCalendar


  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwordRoot
  